### ISSUE TITLE
Storyboard() use in MaterialApp as widget, does not use size

### ISSUE THREAD

**Issue by rydmike** [rodydavis/storyboard#13]
When using Storyboard() in a MaterialApp as a widget, like in example "complete_custom_lanes_builder.dart", it does not pick up the size set for the screens in storyboard, they get the size of the host app.

Tested in version: 0.1.2+1

**Comment by rodydavis** [comment]
To make this work you need to provide a childSize. If you use dynamic screen sizes for the children then it wont know the size to provide.

```dart
childSize: Size(400, 700), // <-- Needed for Child Observer
```

**Comment by rodydavis** [comment]
Fixed on version 0.1.3 and added `sizedChildren` if you need a custom size to show

**Comment by rydmike** [comment]
Thanks, this works now. There are however still some sizing issue remaining, I will post them as separate issues with more specific details and examples.
